version: '3.9'

services:
  cassandra:
    image: cassandra
    ports:
      - '9042:9042'
    restart: always
    environment:
      - CASSANDRA_DC=nosql_intro_datacenter
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
    deploy:
      resources:
        limits:
          memory: 2048M
          cpus: '1.0'
